services:
  api:
    build: .
    container_name: cash_management_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: cash_management_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: